Repository GSG-G8/applicants-system, pull requests merged in 2020-06, with the labels that each got.

#141 create signup page and modified some styles
  client/package-lock.json
  client/package.json
  client/src/assets/images/signup.svg
  client/src/components/application/DotsStepper/index.js
  client/src/components/application/SelectBox/index.js
  client/src/components/application/SelectBox/style.css
  client/src/components/common/Alert/index.js
  client/src/components/common/TextField/index.js
  client/src/components/common/TextField/style.js
  client/src/components/common/card/style.js
  client/src/components/pages/application/Signup/index.css
  client/src/components/pages/application/Signup/index.js
  client/src/utils/application/SignupValidation.js
Labels: Done, Front End, React

#146 added title to page 404
  client/src/components/pages/common/errors/Error-404/index.js
Labels: Done, Front End, React

#132 applicant component responsive dreawer
  client/package-lock.json
  client/package.json
  client/src/components/App/index.js
  client/src/components/application/ResponsiveDrawer/index.js
  client/src/components/application/ResponsiveDrawer/list.js
  client/src/components/application/ResponsiveDrawer/style.js
Labels: Front End, React, React component, applicant, awaiting review

#149 Steps component created
  client/src/assets/images/backGround.svg
  client/src/components/App/index.js
  client/src/components/application/ResponsiveDrawer/list.js
  client/src/components/pages/application/Steps/index.js
  client/src/components/pages/application/Steps/style.css
  server/database/data/steps.js
Labels: Done, Front End, React, React component

#140 component nonlinear stepper
  client/src/components/application/NonlinearStepper/GeneralInfo.js
  client/src/components/application/NonlinearStepper/ProInfos.js
  client/src/components/application/NonlinearStepper/index.js
  client/src/components/application/NonlinearStepper/style.js
  client/src/components/application/SelectBox/index.js
  client/src/components/application/SelectBox/style.css
  client/src/components/common/Typography/index.js
  client/src/utils/application/nLinearStepperValidation.js
  package-lock.json
  server/database/models/applicant.js
Labels: Done, React, React component, applicant, common component

#143 create login front end page
  client/src/assets/images/login.svg
  client/src/components/App/index.js
  client/src/components/common/UserMenu/index.js
  client/src/components/pages/common/Login/index.css
  client/src/components/pages/common/Login/index.js
  client/src/utils/application/LoginValidation.js
  server/middlewares/auth.js
  server/router/index.js
Labels: Done, Front End Routes, React, React component

#151 #35 front end route| technical tasks
  client/src/components/pages/application/Tasks/index.css
  client/src/components/pages/application/Tasks/index.js
  server/controllers/applicant/updateApplicant.js
Labels: Done, Front End, React, applicant

#150 create availability page
  client/src/components/application/NonlinearStepper/GeneralInfo.js
  client/src/components/application/NonlinearStepper/ProInfos.js
  client/src/components/application/NonlinearStepper/index.js
  client/src/components/application/NonlinearStepper/style.js
  client/src/components/pages/application/Accounts/index.css
  client/src/components/pages/application/Accounts/index.js
  client/src/components/pages/application/Availability/availability.json
  client/src/components/pages/application/Availability/index.css
  client/src/components/pages/application/Availability/index.js
Labels: Done, Front End Routes, React

#152 Final project page
  client/src/components/common/TextField/index.js
  client/src/components/pages/application/Project/index.css
  client/src/components/pages/application/Project/index.js
  client/src/components/pages/application/Project/style.css
  client/src/components/pages/application/Signup/index.js
  client/src/utils/application/ProjectValidation.js
  server/controllers/applicant/getRandomProject.js
  server/controllers/applicant/index.js
  server/controllers/applicant/updateApplicant.js
  server/controllers/auth/signup.js
  server/controllers/project/getProjectById.js
  server/router/applicant-router.js
  server/router/index.js
  server/router/project-router.js
Labels: Back End Routes, Done, Front End, React, applicant

#158 fixed Mu helper text css class
  client/src/components/pages/application/Project/index.js
  client/src/components/pages/application/Project/style.css
Labels: Done, Front End, React, applicant, bug

#154 Applicant Profile || front end page
  client/src/components/App/index.css
  client/src/components/App/index.js
  client/src/components/common/UserMenu/index.js
  client/src/components/common/card/style.js
  client/src/components/pages/application/Profile/index.css
  client/src/components/pages/application/Profile/index.js
Labels: Front End Routes, React, React component, awaiting review

#159 Applicant Profile | change checkbox to be disabled
  client/src/components/pages/application/Profile/index.js
Labels: Front End, awaiting review

#157 156 storing values in tasks page
  client/src/components/pages/application/Accounts/index.js
  client/src/components/pages/application/Tasks/index.css
  client/src/components/pages/application/Tasks/index.js
  client/src/utils/application/tasksValidation.js
  server/controllers/applicant/updateApplicant.js
  server/database/data/tasks.js
Labels: Done, Front End, Front End Routes, React, applicant

#160 Made the design responsive to all devices and changed the names of the classes
  client/src/components/application/ResponsiveDrawer/index.js
  client/src/components/application/ResponsiveDrawer/style.js
  client/src/components/common/AppBar/style.css
  client/src/components/pages/application/Accounts/index.css
  client/src/components/pages/application/Project/style.css
  client/src/components/pages/application/Signup/index.css
  client/src/components/pages/application/Signup/index.js
  client/src/components/pages/application/Steps/index.js
  client/src/components/pages/application/Steps/style.css
  client/src/components/pages/common/Home/index.css
  client/src/components/pages/common/Home/index.js
  client/src/components/pages/common/Login/index.css
  client/src/components/pages/common/Login/index.js
  client/src/utils/application/SignupValidation.js
Labels: awaiting review, design

#163 Dashboard | Bar component
  client/src/assets/icons/dashBarIcons/A.png
  client/src/assets/icons/dashBarIcons/B.png
  client/src/assets/icons/dashBarIcons/C.png
  client/src/assets/icons/dashBarIcons/D.png
  client/src/assets/icons/dashBarIcons/E.png
  client/src/assets/icons/dashBarIcons/F.png
  client/src/assets/icons/dashBarIcons/G.png
  client/src/assets/icons/dashBarIcons/H.png
  client/src/assets/icons/dashBarIcons/I.png
  client/src/components/dashboard/Tabs/index.css
  client/src/components/dashboard/Tabs/index.js
Labels: Done, React, React component, common component

#161 Dashboard | Create chart component
  client/package-lock.json
  client/package.json
  client/src/assets/icons/dashBarIcons/A.png
  client/src/assets/icons/dashBarIcons/B.png
  client/src/assets/icons/dashBarIcons/C.png
  client/src/assets/icons/dashBarIcons/D.png
  client/src/assets/icons/dashBarIcons/E.png
  client/src/assets/icons/dashBarIcons/F.png
  client/src/assets/icons/dashBarIcons/G.png
  client/src/assets/icons/dashBarIcons/H.png
  client/src/assets/icons/dashBarIcons/I.png
  client/src/components/dashboard/Tabs/index.css
  client/src/components/dashboard/Tabs/index.js
  client/src/components/dashboard/chart/index.js
  server/middlewares/auth.js
Labels: Done, React, React component, admin

#153 added Submit page
  client/package-lock.json
  client/package.json
  client/src/components/App/index.js
  client/src/components/application/ResponsiveDrawer/index.js
  client/src/components/application/ResponsiveDrawer/list.js
  client/src/components/pages/application/Submit/index.css
  client/src/components/pages/application/Submit/index.js
  server/controllers/applicant/updateApplicant.js
  server/router/index.js
Labels: Front End, React, applicant, awaiting review

#155 added redirect in app page
  client/src/components/application/ResponsiveDrawer/style.js
  client/src/components/common/AppBar/index.js
  client/src/components/common/AppBar/style.css
  client/src/components/common/UserMenu/index.js
  client/src/components/common/UserMenu/style.js
  client/src/components/pages/application/Steps/index.js
  client/src/components/pages/application/Steps/style.css
  client/src/components/pages/application/Tasks/index.css
  client/src/components/pages/application/Tasks/index.js
  server/database/models/applicant.js
Labels: Done, Front End, Front End Routes, React

#164 change availablity style
  client/src/components/application/NonlinearStepper/index.js
  client/src/components/pages/application/Accounts/index.css
  client/src/components/pages/application/Accounts/index.js
  client/src/components/pages/application/Availability/index.css
  client/src/components/pages/application/Availability/index.js
Labels: Done, applicant

#165 Dashboard Statics Page
  client/src/assets/images/backgroundDash.svg
  client/src/assets/images/dashbackground.png
  client/src/components/common/card/style.js
  client/src/components/dashboard/chart/index.js
  client/src/components/pages/admin/Dashboard/index.css
  client/src/components/pages/admin/Dashboard/index.js
Labels: Done, Front End, React, React component

#170 DashBoard | submitted application Page
  client/package-lock.json
  client/package.json
  client/src/components/dashboard/Tabs/index.js
  client/src/components/pages/admin/Submitted_all/index.css
  client/src/components/pages/admin/Submitted_all/index.js
Labels: Done, Front End Routes, React, React component, admin

#167 Code Refactoring
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/gsg-logo.png
  client/public/index.html
  client/src/components/App/index.js
  client/src/components/application/NonlinearStepper/GeneralInfo.js
  client/src/components/application/NonlinearStepper/ProInfos.js
  client/src/components/common/AppBar/index.js
  client/src/components/common/UserMenu/index.js
  client/src/components/pages/application/Accounts/index.js
  client/src/components/pages/application/Availability/index.js
  client/src/components/pages/application/Profile/index.js
  client/src/components/pages/application/Project/index.js
  client/src/components/pages/application/Signup/index.js
  client/src/components/pages/application/Steps/index.js
  client/src/components/pages/application/Submit/index.js
  client/src/components/pages/application/Tasks/index.js
  client/src/components/pages/common/errors/Error-404/index.js
  client/src/utils/application/nLinearStepperValidation.js
  server/controllers/auth/login.js
  server/controllers/auth/signup.js
  server/database/models/applicant.js
Labels: Back End, Back End Routes, Done, Express, Front End, Front End Routes, React, React component, admin, applicant, common component, database

#174 create completed application page - this page is clone from submitted…
  client/src/components/pages/admin/Completed/index.js
Labels: Done, Front End, Front End Routes, React, admin

#176 added logout in dashboard
  client/src/components/App/index.js
  client/src/components/dashboard/Tabs/index.js
Labels: Done

#172 Front-end Route | opened applications
  client/src/components/pages/admin/Opened/index.css
  client/src/components/pages/admin/Opened/index.js
Labels: Done, Front End, Front End Routes, React, admin

#180 added Accepted Application page and route in app
  client/src/components/App/index.js
  client/src/components/dashboard/Tabs/index.js
  client/src/components/pages/admin/Accepted/index.js
Labels: Done, Front End, React, applicant

#181 update table to include export function
  client/src/components/pages/admin/Completed/index.js
  client/src/components/pages/admin/Opened/index.js
  client/src/components/pages/admin/Submitted_all/index.js
Labels: Done, React, admin

#184 upgrade the icons in tab bar .
  client/src/assets/icons/dashBarIcons/accepted.png
  client/src/assets/icons/dashBarIcons/acceptedImg.png
  client/src/assets/icons/dashBarIcons/add.png
  client/src/assets/icons/dashBarIcons/addImg.png
  client/src/assets/icons/dashBarIcons/admin.png
  client/src/assets/icons/dashBarIcons/adminImg.png
  client/src/assets/icons/dashBarIcons/completed.png
  client/src/assets/icons/dashBarIcons/completedImg.png
  client/src/assets/icons/dashBarIcons/home.png
  client/src/assets/icons/dashBarIcons/homeImg.png
  client/src/assets/icons/dashBarIcons/logout.png
  client/src/assets/icons/dashBarIcons/logoutImg.png
  client/src/assets/icons/dashBarIcons/search.png
  client/src/assets/icons/dashBarIcons/submitted.png
  client/src/assets/icons/dashBarIcons/submittedImg.png
  client/src/assets/icons/dashBarIcons/tools.png
  client/src/assets/icons/dashBarIcons/toolsImg.png
  client/src/components/dashboard/Tabs/index.css
  client/src/components/dashboard/Tabs/index.js
Labels: Done, React, React component, admin

#182 Applicant track Edits
  client/src/components/application/DotsStepper/index.js
  client/src/components/common/AppBar/index.js
  client/src/components/dashboard/Tabs/index.js
  client/src/components/pages/application/Profile/index.js
  client/src/components/pages/application/Submit/index.js
  client/src/utils/application/ProjectValidation.js
  server/controllers/auth/signup.js
  server/controllers/cohort/getLastCohort.js
  server/router/cohort-router.js
  server/router/index.js
Labels: Done, Front End, React, admin, applicant

#185 update the availability form Page
  client/src/components/application/NonlinearStepper/GeneralInfo.js
  client/src/components/application/NonlinearStepper/ProInfos.js
  client/src/components/application/NonlinearStepper/index.js
  client/src/components/application/NonlinearStepper/questions.js
  client/src/components/application/NonlinearStepper/style.js
  client/src/utils/application/nLinearStepperValidation.js
Labels: Done, React, React component, applicant

#188 Dashboard Style Refactor
  client/src/components/dashboard/Tabs/index.css
  client/src/components/pages/admin/Completed/index.css
  client/src/components/pages/admin/Completed/index.js
  client/src/components/pages/admin/Statistics/index.css
  client/src/components/pages/admin/Submitted_Id/index.css
Labels: Done, design

#171 Front-end Route | applicant page (admin side)
  client/src/components/App/index.js
  client/src/components/pages/admin/Accepted/index.js
  client/src/components/pages/admin/Completed/index.js
  client/src/components/pages/admin/Submitted_Id/index.css
  client/src/components/pages/admin/Submitted_Id/index.js
  server/controllers/applicant/updateApplicant.js
  server/router/admin-router.js
Labels: Done, Front End, Front End Routes, React, admin

#186 Refactor for applicatns side style
  client/src/components/App/index.css
  client/src/components/App/index.js
  client/src/components/application/NonlinearStepper/GeneralInfo.js
  client/src/components/application/NonlinearStepper/ProInfos.js
  client/src/components/application/ResponsiveDrawer/index.js
  client/src/components/application/ResponsiveDrawer/style.js
  client/src/components/common/Alert/index.js
  client/src/components/common/AppBar/index.css
  client/src/components/common/AppBar/index.js
  client/src/components/pages/admin/Dashboard/index.css
  client/src/components/pages/admin/Opened/index.css
  client/src/components/pages/admin/Submitted_Id/index.css
  client/src/components/pages/admin/Submitted_Id/index.js
  client/src/components/pages/admin/Submitted_all/index.css
  client/src/components/pages/application/Accounts/index.css
  client/src/components/pages/application/Accounts/index.js
  client/src/components/pages/application/Availability/index.css
  client/src/components/pages/application/Availability/index.js
  client/src/components/pages/application/Profile/index.css
  client/src/components/pages/application/Profile/index.js
  client/src/components/pages/application/Project/index.css
  client/src/components/pages/application/Project/index.js
  client/src/components/pages/application/Project/style.css
  client/src/components/pages/application/Signup/index.css
  client/src/components/pages/application/Steps/index.css
  client/src/components/pages/application/Steps/index.js
  client/src/components/pages/application/Steps/style.css
  client/src/components/pages/application/Submit/index.css
  client/src/components/pages/application/Tasks/index.css
  client/src/components/pages/application/Tasks/index.js
  client/src/components/pages/common/Home/index.css
  client/src/components/pages/common/Login/index.css
  client/src/components/pages/common/errors/Error-404/index.css
Labels: Done, Front End, design

#190 189 fix full name validation
  client/src/components/application/NonlinearStepper/GeneralInfo.js
  client/src/components/pages/application/Signup/index.js
  client/src/utils/application/nLinearStepperValidation.js
Labels: Done, Front End, applicant

#192 fix accept button | Admin side applicant page
  client/src/components/pages/admin/Submitted_Id/index.js
  client/src/components/pages/application/Steps/index.js
  server/controllers/applicant/updateApplicant.js
Labels: Done, React, admin, bug

#198 fixed application steps title
  client/src/components/pages/application/Steps/index.js
Labels: Done, React, applicant

#201 fixed opened application page
  client/src/components/pages/admin/Opened/index.js
Labels: Done, React, admin, bug

#203 fix availability style
  client/src/components/pages/application/Availability/index.css
Labels: Done

#208 updated readme
  README.md
Labels: Done, Read Me, documentation, enhancement

#211 fixed submit bug in page submit
  client/src/components/pages/application/Submit/index.js
Labels: Done, Front End, React, applicant
